name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Npm install
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm i

      - name: Run build lib
        run: npm run build:lib

      - name: Run build playground
        run: npm run build
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Npm install
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm i

      - name: Run tests
        run: npm run test:lib:headless
